### ISSUE TITLE
[Feat] recipe entity 만들기

### ISSUE THREAD

**Issue by sujeongmoon** [LeeChangHyeong/igeo-mubwotna#1]
**🌟 Issue : Feature**
recipe entity 만들기

**Description**
id, user_id, title, content, created_at, modified_at이 포함된 entity를 만듭니다.

**Todo**
- [x] 엔티티 생성
- [x] 연관관계 설정

**Reference(Optional)**

**Comment by LeeChangHyeong** [comment]
수정님!
이슈 너무 잘 만들어주시고 계신데 Labels랑 Assignees도 지정해 놓으면 더 좋을 것 같습니다~~
